name: clang

on:
  push:
    branches: [ master, fix-ci ]

jobs:
  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: DoozyX/clang-format-lint-action@v0.10
        with:
          style: file
          source: 'source plugins'
          clangFormatVersion: 11
          inplace: True
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Clang Robot
          author_email: clang-robot@the-starport.net
          message: 'clang-format changes'
          fetch: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}