# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: DoozyX/clang-format-lint-action@v0.10
        with:
          style: file
          source: 'source plugins'
          clangFormatVersion: 11
          inplace: True
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: Clang Robot
          author_email: clang-robot@the-starport.net
          message: 'clang-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: windows-latest
    needs: [format]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: ilammy/msvc-dev-cmd@v1.5.0
        with:
          arch: x86

      - name: Build
        run: msbuild.exe "${env:GITHUB_WORKSPACE}\project\FLHook.sln" /t:Build /p:Configuration=Release /p:Platform=Win32

