# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  lint-and-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.3.0
        
      - name: Lint with Clang Format
        run: |
              clang-format.exe -style=llvm -i source plugins misc FLHookSDK/include
              $status = git status --porcelain source plugins misc FLHookSDK/include
              if($status) {
                git diff source plugins misc FLHookSDK/include
                exit 1
              }
        
      - name: Build
        run: msbuild.exe "${env:GITHUB_WORKSPACE}\project\FLHook.sln" /t:Build /p:Configuration=Release /p:Platform=Win32
          
