# This runs SonarCloud to detect code issues.

name: SonarScan

on:
  workflow_run:
    workflows: [SonarBuild]
    types: [completed]

jobs:    
  build:
    runs-on: windows-latest
    env:
      SONAR_SCANNER_VERSION: 4.6.1.2450
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
      COVERAGE_RESULTS: coverage_results
    steps:
      - name: Download Sonar Build
        uses: actions/download-artifact@v3
        with:
          name: sonar-build-PR
          path: ${{ env.BUILD_WRAPPER_OUT_DIR }}
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner --define sonar.host.url="${{ env.SONAR_SERVER_URL }}" --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"
